ALTER TYPE "PartyRole" RENAME VALUE 'MEMBER' TO 'MEMBRE';
ALTER TYPE "PartyRole" RENAME VALUE 'FOUNDER' TO 'FONDATEUR';
ALTER TYPE "PartyRole" RENAME VALUE 'SPOKESPERSON' TO 'PORTE_PAROLE';
ALTER TYPE "PartyRole" RENAME VALUE 'COORDINATOR' TO 'COORDINATEUR';
ALTER TYPE "PartyRole" RENAME VALUE 'HONORARY_PRESIDENT' TO 'PRESIDENT_HONNEUR';
ALTER TYPE "PartyRole" RENAME VALUE 'SECRETARY_GENERAL' TO 'SECRETAIRE_GENERAL';
