import { describe, it, expect } from "vitest";
import { renderConfirmDoiHtml, renderConfirmDoiText } from "../render-confirm-doi";

describe("renderConfirmDoiHtml", () => {
  it("substitutes confirmUrl in the button href", () => {
    const url = "https://poligraph.fr/api/newsletter/confirm?token=abc123";
    const html = renderConfirmDoiHtml({ confirmUrl: url });
    expect(html).toContain(url);
    expect(html).not.toContain("{{confirmUrl}}");
  });

  it("includes a confirmation prompt in French", () => {
    const html = renderConfirmDoiHtml({
      confirmUrl: "https://poligraph.fr/api/newsletter/confirm?token=x",
    });
    expect(html).toMatch(/Confirme.*inscription/i);
    expect(html).toContain("Confirmer mon inscription");
  });

  it("escapes nothing (URLs are caller-controlled and trusted)", () => {
    // We don't escape because the URL is built server-side from a base + token
    // generated by crypto.randomBytes. No user input flows here.
    const url = "https://poligraph.fr/api/newsletter/confirm?token=AbC-1_2-x";
    const html = renderConfirmDoiHtml({ confirmUrl: url });
    expect(html).toContain(url);
  });
});

describe("renderConfirmDoiText", () => {
  it("includes the confirmUrl as plain text", () => {
    const url = "https://poligraph.fr/api/newsletter/confirm?token=abc";
    const text = renderConfirmDoiText({ confirmUrl: url });
    expect(text).toContain(url);
  });

  it("does not contain HTML tags", () => {
    const text = renderConfirmDoiText({
      confirmUrl: "https://poligraph.fr/api/newsletter/confirm?token=x",
    });
    expect(text).not.toMatch(/<[a-z]+>/i);
  });
});
